import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium, type Browser } from 'playwright';

// Real Chromium, driven against the real compiled app — not a simulation.
// Run via `npm run e2e` (builds first, then this file).

// Compiled by tsconfig.e2e.json with rootDir "tests/e2e" -> outDir "dist-e2e",
// which flattens this file straight into dist-e2e/ at runtime (no nested
// tests/e2e/ subfolder survives the build) — so it's one level up to app/,
// not two.
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DIST_DIR = path.resolve(__dirname, '../dist');
const PORT = 5199;

const MIME: Record<string, string> = {
  '.html': 'text/html',
  '.js': 'text/javascript',
  '.css': 'text/css',
};

let server: http.Server;
let browser: Browser;

before(async () => {
  server = http.createServer((req, res) => {
    const urlPath = (req.url === '/' ? '/index.html' : req.url) ?? '/index.html';
    const filePath = path.join(DIST_DIR, decodeURIComponent(urlPath.split('?')[0]!));
    fs.readFile(filePath, (err, data) => {
      if (err) {
        res.writeHead(404);
        res.end('Not found');
        return;
      }
      res.writeHead(200, { 'Content-Type': MIME[path.extname(filePath)] ?? 'application/octet-stream' });
      res.end(data);
    });
  });
  await new Promise<void>((resolve) => server.listen(PORT, resolve));
  browser = await chromium.launch();
});

after(async () => {
  await browser.close();
  await new Promise<void>((resolve) => server.close(() => resolve()));
});

async function readLastOtp(page: import('playwright').Page, identifier: string): Promise<string> {
  return page.evaluate(async (id) => {
    await new Promise((r) => setTimeout(r, 50));
    return (window as unknown as { __backend: { __debugGetLastOtp: (i: string) => string } }).__backend.__debugGetLastOtp(id);
  }, identifier);
}

test('onboarding: nothing to playing, under 60 seconds, with zero console errors', async () => {
  const page = await browser.newPage();
  const consoleErrors: string[] = [];
  page.on('pageerror', (e) => consoleErrors.push(String(e)));
  page.on('console', (msg) => {
    if (msg.type() === 'error') consoleErrors.push(msg.text());
  });

  await page.goto(`http://localhost:${PORT}/`);

  const start = Date.now();
  await page.getByTestId('ob-get-started').click();
  await page.getByTestId('ob-name').fill('Alex');
  await page.getByTestId('ob-contact').fill('alex@example.com');
  await page.getByTestId('ob-continue').click();

  const code = await readLastOtp(page, 'alex@example.com');
  assert.match(code, /^\d{6}$/, 'a real 6-digit code was generated by the backend');

  await page.getByTestId('ob-otp').fill(code);
  await page.waitForSelector('[data-testid="ob-start-playing"]', { state: 'visible' });
  await page.getByTestId('ob-start-playing').click();
  // Landing takes you to the Score tab (the app shell's default); "playing" is
  // reached the moment the Trip tab's log button is one tap away.
  await page.waitForSelector('[data-testid="tab-trip"]', { state: 'visible' });
  await page.getByTestId('tab-trip').click();
  await page.waitForSelector('[data-testid="open-log"]', { state: 'visible' });

  const elapsed = Date.now() - start;
  assert.ok(elapsed < 60_000, `onboarding took ${elapsed}ms, expected under 60000ms`);
  assert.deepEqual(consoleErrors, [], 'no console or page errors during onboarding');

  await page.close();
});

test('a wrong OTP is rejected with a visible error, not a silent failure', async () => {
  const page = await browser.newPage();
  await page.goto(`http://localhost:${PORT}/`);
  await page.getByTestId('ob-get-started').click();
  await page.getByTestId('ob-name').fill('Alex');
  await page.getByTestId('ob-contact').fill('wrongcode@example.com');
  await page.getByTestId('ob-continue').click();
  await page.getByTestId('ob-otp').fill('000000');
  await page.waitForSelector('#ob-verify-error:not(:empty)');
  const message = await page.locator('#ob-verify-error').textContent();
  assert.match(message ?? '', /didn.t match/i);
  await page.close();
});

test('core loop: logging a call updates points and the streak in the real UI', async () => {
  const page = await browser.newPage();
  await page.goto(`http://localhost:${PORT}/`);
  await page.getByTestId('ob-get-started').click();
  await page.getByTestId('ob-name').fill('Jamie');
  await page.getByTestId('ob-contact').fill('jamie@example.com');
  await page.getByTestId('ob-continue').click();
  const code = await readLastOtp(page, 'jamie@example.com');
  await page.getByTestId('ob-otp').fill(code);
  await page.waitForSelector('[data-testid="ob-start-playing"]');
  await page.getByTestId('ob-start-playing').click();
  await page.getByTestId('tab-trip').click();

  await page.getByTestId('open-log').click();
  await page.locator('[data-testid="color-chips"] .chip', { hasText: 'Olympic Blue' }).click();
  await page.locator('#body-style button[data-style="Convertible"]').click();
  await page.getByTestId('submit-log').click();

  await page.waitForFunction(() => document.querySelector('[data-testid="call-list"]')?.textContent?.includes('+2'));
  const streakText = await page.getByTestId('streak-chip').textContent();
  assert.match(streakText ?? '', /1-day streak/);

  await page.close();
});

test('a solo player (no invite code entered) sees no rivalry scoreboard, per SPEC.md §3.2', async () => {
  const page = await browser.newPage();
  await page.goto(`http://localhost:${PORT}/`);
  await page.getByTestId('ob-get-started').click();
  await page.getByTestId('ob-name').fill('Nicole');
  await page.getByTestId('ob-contact').fill('nicole-round@example.com');
  await page.getByTestId('ob-continue').click();
  const code = await readLastOtp(page, 'nicole-round@example.com');
  await page.getByTestId('ob-otp').fill(code);
  await page.waitForSelector('[data-testid="ob-start-playing"]');
  await page.getByTestId('ob-start-playing').click();

  // This user started solo (no invite code), so the Score tab should branch
  // to the solo card, not a rivalry scoreboard.
  await page.waitForSelector('[data-testid="score-solo"]', { state: 'visible' });
  const roundRow = await page.locator('[data-testid="score-row"]').count();
  assert.equal(roundRow, 0, 'a solo player sees no rivalry scoreboard, per SPEC.md §3.2');

  await page.close();
});

async function onboardSolo(
  page: import('playwright').Page,
  name: string,
  identifier: string,
): Promise<void> {
  await page.goto(`http://localhost:${PORT}/`);
  await page.getByTestId('ob-get-started').click();
  await page.getByTestId('ob-name').fill(name);
  await page.getByTestId('ob-contact').fill(identifier);
  await page.getByTestId('ob-continue').click();
  const code = await readLastOtp(page, identifier);
  await page.getByTestId('ob-otp').fill(code);
  await page.waitForSelector('[data-testid="ob-start-playing"]');
  await page.getByTestId('ob-start-playing').click();
  await page.waitForSelector('[data-testid="score-solo"]');
}

test('all five tabs render their own screen without console errors', async () => {
  const page = await browser.newPage();
  const consoleErrors: string[] = [];
  page.on('pageerror', (e) => consoleErrors.push(String(e)));
  await onboardSolo(page, 'Casey', 'casey-tabs@example.com');

  const tabs: Array<[string, string]> = [
    ['tab-trip', 'open-log'],
    ['tab-team', 'team-none'],
    ['tab-history', 'history-screen'],
    ['tab-rules', 'rules-none'],
    ['tab-score', 'score-solo'],
  ];
  for (const [tab, expectedTestId] of tabs) {
    await page.getByTestId(tab).click();
    await page.waitForSelector(`[data-testid="${expectedTestId}"]`, { state: 'visible' });
  }
  assert.deepEqual(consoleErrors, []);
  await page.close();
});

test('starting a rivalry from the solo Score tab switches to the rivalry scoreboard', async () => {
  const page = await browser.newPage();
  page.on('dialog', (dialog) => void dialog.accept('Team Reineke'));
  await onboardSolo(page, 'Nicole', 'nicole-startrivalry@example.com');

  await page.getByTestId('start-rivalry').click();
  await page.waitForSelector('[data-testid="score-rivalry"]', { state: 'visible' });
  const teamAName = await page.locator('#team-a-name').textContent();
  assert.equal(teamAName, 'Team Reineke');
  const teamBName = await page.locator('#team-b-name').textContent();
  assert.match(teamBName ?? '', /waiting/i, 'no second team has joined yet');

  await page.getByTestId('tab-team').click();
  await page.waitForSelector('[data-testid="team-roster"]', { state: 'visible' });
  const inviteCode = await page.getByTestId('team-invite-code').textContent();
  assert.match(inviteCode ?? '', /^BUG-/);

  await page.close();
});

test('the Rules screen round-target stepper actually persists through the backend', async () => {
  const page = await browser.newPage();
  page.on('dialog', (dialog) => void dialog.accept('Team Ouellette'));
  await onboardSolo(page, 'Daniel', 'daniel-rules@example.com');
  await page.getByTestId('start-rivalry').click();
  await page.waitForSelector('[data-testid="score-rivalry"]');

  await page.getByTestId('tab-rules').click();
  await page.waitForSelector('[data-testid="rules-screen"]', { state: 'visible' });
  const before = await page.locator('#target-val').textContent();
  assert.equal(before, '21', 'the default round target is 21');

  await page.locator('#target-plus').click();
  await page.locator('#target-plus').click();
  const after = await page.locator('#target-val').textContent();
  assert.equal(after, '23');

  await page.close();
});
